### ISSUE TITLE
make ores listed as minable with netherite instead of wooden

### ISSUE THREAD

**Issue by BamsyTheSergal** [SmartStreamLabs/MysticRift-Ultimate-400-Blocks#1]
any pickaxe can easily mine the ores, but only drop when mined with netherite

**Comment by SmartStreamLabs** [comment]
Thank you for your report. can you give us more details? like: game version 1.20.1 / 1.21 ? and what mod loader: fabric, neoforge ?

**Comment by BamsyTheSergal** [comment]
oh yes sorry, it was forge 1.20.1, mod version 15.2.3,

**Comment by SmartStreamLabs** [comment]
Yes, thank you, I'll take a look in one of our test servers. 

We will keep you informed!

**Comment by SmartStreamLabs** [comment]
We have a update ready, hopefully we fixed it! let us know

https://www.curseforge.com/minecraft/mc-mods/mysticrift-ultimate-blocks/files/all?page=1&pageSize=20
